### ISSUE TITLE
Cannot be shared between threads safely

### ISSUE THREAD

**Issue by SheIITear** [shekohex/wadump#1]
Hi, first thank you for making this tool :)!

When I try to run: 
> cargo run -- --help

I get an error which I copy pasted to here: https://del.dog/ycapufiqyv.txt

**Comment by shekohex** [comment]
Hello, could you provide which operating system you use? And which rust version?

**Comment by SheIITear** [comment]
I use debian 10 and rust version is 1.45.0.

**Comment by shekohex** [comment]
I guess that error happened because I use `anyhow` crate which requires the error to be `Send` 
And apparently that the error from `keyring` crate on linux targets is not `Send`.
I guess the fix for this is to use `Box<dyn std::error::Error>` as error type instead of the one from `anyhow`

I will try to make a fix soon in the next morning.. or if you could help and fix that.. it would be awesome :)

**Comment by SheIITear** [comment]
No problem. I was able to fix and run it properly :).

**Comment by shekohex** [comment]
closed in #3
